// -----------------------------------------------------------------------------
// MANIFOLD CLOUD CONFIGURATION — TELEVISA
// -----------------------------------------------------------------------------
// This file combines the former cloud.ts and cluster.ts configurations. It
// defines the hardware and licenses available to manifold CLOUD, cluster-level
// networking and protocol settings, generated layouts, services, and 3D LUTs.
// The completed payload is posted to the /configuration API endpoint below.

// Layout helpers create the default parameter structures and turn the enabled
// layout families and raster configurations into configuration records.
import ManifoldCloudAPI from './manifold_cloud_api.js';
import {
        generate_layouts_parameters,
        generate_all_layouts,
        configure_default_ppm_layouts,
        configure_existing_umd_modes,
        configure_existing_omd_modes,
        RASTER_1920x1080_ID,
        RASTER_3840x2160_ID,
        DEFAULT_LAYOUTS_ID,
        OUTSIDE_LAYOUTS_UMD_ID,
        OUTSIDE_LAYOUTS_UMD_PPM_ID,
        OUTSIDE_LAYOUTS_UMD_TALLY_ID,
        OUTSIDE_LAYOUTS_UMD_PPM_TALLY_ID,
        INSIDE_LAYOUTS_UMD_ID,
        INSIDE_LAYOUTS_UMD_PPM_ID,
        INSIDE_LAYOUTS_UMD_TALLY_ID,
        INSIDE_LAYOUTS_UMD_PPM_TALLY_ID,
        USER_0_LAYOUTS_ID,
        USER_1_LAYOUTS_ID,
        USER_2_LAYOUTS_ID,
        USER_3_LAYOUTS_ID,
        USER_4_LAYOUTS_ID,
        LAYOUTS_CONFIGS_NUM,
        clone,
        get_default_md
} from './layouts_default.js';
import type {
        MonitorDisplayMode,
        PpmValueConfiguration
} from './layouts_default.js';
import * as fs from 'fs/promises';
import * as path from 'path';

// =============================================================================
// USER-EDITABLE CONFIGURATION
// =============================================================================

const api_configuration = {
   url      : 'http://127.0.0.1/v1/manifold/',
   // Alternative remote API URL: 'http://172.16.218.169/v1/manifold/'
   username : 'admin',
   password : 'password',
   timeout  : 180000
};

// Select which areas are replaced when this configuration is applied. Set an
// area to false to leave its current state unchanged.
const configuration_areas = {
   // Reset all selected areas before loading this configuration.
   reset           : true,
   hardware        : true,
   clusters        : true,
   licenses        : true,
   services        : true,
   sources_routing : true,
   luts3D          : true,
   system_layouts  : true,
   user_layouts    : true
};

// System and user layouts generated by get_layouts().
const layout_configuration = {
   families : {
      standard : true,
      featured : true,
      remote   : true,
      director : true,
      vt_coord : true,
      big      : true,
      riot     : false
   },

   // Set the default text source for every existing UMD and OMD cell. Supply
   // one mode for all cells or an array for per-cell mapping; if a display has
   // more cells than entries, the last entry is reused.
   //
   // Monitor-display mode options:
   //   'label', 'parent_video_source_name',
   //   'parent_video_source_standard', 'parent_video_source_tally_label',
   //   'parent_video_source_user_label_0',
   //   'parent_video_source_user_label_1',
   //   'parent_video_source_standard_interface',
   //   'parent_video_source_standard_tcs'.
   default_umd_modes : ['label'] as MonitorDisplayMode[],
   default_omd_modes : ['label'] as MonitorDisplayMode[],

   custom_umd_layout : {
      slot               : USER_4_LAYOUTS_ID,
      based_on           : OUTSIDE_LAYOUTS_UMD_ID,
      name               : 'outside (umd dual)',
      video_border_width : 0,
      alignment          : 'outside',
      width              : 1.0,
      cells              : [
         {mode : 'parent_video_source_standard' as MonitorDisplayMode,width : 0.4,border_width : 1},
         {mode : 'parent_video_source_name' as MonitorDisplayMode,width : 0.6,border_width : 1}
      ]
   },

   alarms : {
      // Show alarms on the selected style, including a logo when no source is
      // assigned. PPM channel mapping is configured globally below.
      style                       : OUTSIDE_LAYOUTS_UMD_PPM_TALLY_ID,
      enable                      : true,
      show_logo_when_unassigned   : true
   },

   // Presets:
   //   split_16ch: left channels 0-7, right channels 8-15
   //   mirrored_8ch: both sides show channels 0-7
   //   quad_4ch_zero: two meters per side, each showing channels 0-3
   ppm : {
      mode              : 'preset',
      preset            : 'split_16ch',
      // Manual values are used when mode is 'manual'. Arrays provide per-meter
      // control; for example, [2,2] channels with offsets [0,2] creates meters
      // for channels 0-1 and 2-3.
      meters_left       : 1,
      channels_left     : 8,
      offset_left       : 0,
      meters_right      : 1,
      channels_right    : 8,
      offset_right      : 8,
      width             : 0.05,
      width_max         : 0.09,
      channel_min_width : 4
   } as PpmLayoutConfiguration,

   enabled_styles : {
      [DEFAULT_LAYOUTS_ID]                : false,
      [OUTSIDE_LAYOUTS_UMD_ID]            : false,
      [OUTSIDE_LAYOUTS_UMD_PPM_ID]        : false,
      [OUTSIDE_LAYOUTS_UMD_TALLY_ID]      : false,
      [OUTSIDE_LAYOUTS_UMD_PPM_TALLY_ID]  : true,
      [INSIDE_LAYOUTS_UMD_ID]             : false,
      [INSIDE_LAYOUTS_UMD_PPM_ID]         : false,
      [INSIDE_LAYOUTS_UMD_TALLY_ID]       : false,
      [INSIDE_LAYOUTS_UMD_PPM_TALLY_ID]   : false,
      [USER_0_LAYOUTS_ID]                 : false,
      [USER_1_LAYOUTS_ID]                 : false,
      [USER_2_LAYOUTS_ID]                 : false,
      [USER_3_LAYOUTS_ID]                 : false,
      [USER_4_LAYOUTS_ID]                 : false
   },

   rasters : {
      [RASTER_1920x1080_ID] : {enable : false,background : 'black'},
      [RASTER_3840x2160_ID] : {enable : true, background : 'black'}
   }
};

// Service instances generated for each configured cluster.
const service_configuration = {
   // Common video_raster_id values:
   //   '720x486', '720x576', '1280x720', '1920x1035', '1920x1080',
   //   '2048x1080', '3840x2160', '4096x2160', '7680x4320', '8192x4320'.
   // Common video_refresh_rate_id values:
   //   'p23.98Hz', 'sF23.98Hz', 'p24Hz', 'sF24Hz', 'p25Hz', 'sF25Hz',
   //   'p29.97Hz', 'sF29.97Hz', 'p30Hz', 'sF30Hz', 'p47.95Hz',
   //   'i47.95Hz', 'p48Hz', 'i48Hz', 'p50Hz', 'i50Hz', 'p59.94Hz',
   //   'i59.94Hz', 'p60Hz', 'i60Hz', 'p100Hz', 'p119.88Hz', 'p120Hz'.
   video_test_generators : {
      count                 : 0,
      video_raster_id       : '1920x1080',
      video_refresh_rate_id : 'p59.94Hz',
      ip_addresses_range_id : 2,
      pattern_start_index   : 1,
      inserted_id_enable    : true,
      frame_id              : 0,
      input_frames_num      : 1,
      colour_c0             : 512,
      colour_c1             : 512,
      colour_c2             : 512,
      insert_motion_enable  : true,
      insert_motion_colour  : 0,
      enable_output_rl      : false,
      output_stream_enable  : true
   },

   multiviewer_heads : [],

   multiviewer_defaults : {
      audio_inputs_per_video_input_max_num    : 1,
      metadata_inputs_per_video_input_max_num : 1,
      display_mode                            : 'on',
      ip_addresses_range_id                   : 4
   },

   udx : {
      count                 : 36,
      video_raster_id       : '1920x1080',
      video_refresh_rate_id : 'i59.94Hz',
      ip_addresses_range_id : 4
   }
};

// 3D LUTs loaded from local .cube files by get_luts3D().
const luts_directory = './3dluts/LUTS_for_Hardware_Devices_TypeIII_CUBE_LUT_Format';

const hardware_configuration = {
   // Hardware inventory. A node is a server reachable at ctrl_ipaddr;
   // on_node_id identifies each accelerator within that server.
   // Supported accelerator_type values include:
   //   'Bittware:520N-MX', 'prodesign:FALCON-Stratix', 'arkona:AT300'
   nodes : [
      {
         name        : 'FALCON-NEST - 0',
         ctrl_ipaddr : '127.0.0.1',
         accelerators : [
            {accelerator_type : 'prodesign:FALCON-Stratix',on_node_id : 0},
            {accelerator_type : 'prodesign:FALCON-Stratix',on_node_id : 1}
         ]
      }
   ],

   // License tokens make licensed capacity/features available to the
   // configured hardware and clusters.
   licenses : [
      {name : 'license key 1',token : 'eyJhbGciOiJQUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE4MTE1OTQ2MzYsImlhdCI6MTc4MDAzNzY4NCwibWFuaWZvbGQtY2xvdWQtY2hpcC1pZHMiOiJbXCIweDY4NzY2OThBMTE3NjUxNUJcIixcIjB4Njg3NzBGOEE3RDhEQ0Q3MVwiXSIsIm1hbmlmb2xkLWNsb3VkLXBvaW50cyI6IjEyNjAiLCJtYW5pZm9sZC1jbG91ZC1zeXN0ZW0taWRzIjoiW1wiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwXCJdIiwibWFuaWZvbGQtY2xvdWQtdXBkYXRlcy1lbmFibGUiOiJ0cnVlIn0.MnBsWWZHHABFAgN_9Spl35dn-J0s4O1RYLlQdyenYzEDunX-6w4292Pzkb3yzwaHYuERcaGXlsOAnEicEuJ3lP4q8wlggflemiiaQn9PMlEvwZ9YmDWOVSVBm7wQ-my_-s1hMbRgVp5ETHFhyb3fYt3c4XGs73Ek96m7paLnaexvDF6Q25Cd3FzxfhBRSy8cEUZv0Qj2rPV12Bo8I3ExVVdLK0JO1mXYtU6sveachnHlDSli-LSwNHCewabphRXJzaKrEi1qZScX4R93AjHLrQyMUfbTrIM7UdmO7Q3ripqrPnLoR9BKHGhGn9tIdaYk_oVSMVIeZInWNSNcndJ_m6wm-TQwgKI82kM26rK8Bwd6BI9UYTyCMZ8DTCvtlPqNI-buy1hrC8yPlSnRp2ljNECV9fMKrbMCWh1zzREN7EdvGasZYELEdb6IXpFLUVmQtDdpEpd7M9MQz8_3xd9Bo7_ggtHPeT7_aWhHjUVRbE9bIcFYyvc7Tnqn1BNrVohhQIZcgV2hACZLE31EHx3y1Gh4UapuPwFsI4cKtqdsM5SXXhQ4wltJYpgasZj8h80-pXkjxgjHY_blzRhMkH3OhP-qMvTa8bmwDyp7_3dzCebLD2YUCIJWuUdeWWGeTXBjITxIDxC_a5CZqNQFmBtxFY1vRkezzRrlbSTJ6Lrv9e8'}
   ],

   // Each entry declares a cluster and the hardware, address ranges, and
   // services assigned to it.
   clusters : [
      {
         name    : 'UDX Cluster 1',
         // A stable UUID. A fixed value preserves its NMOS device identity
         // across restarts and configuration reloads.
         id_uuid : 'c1a92ebe-fe73-46ba-8f15-e9f35ea01ae5',

         // Assign a complete node by name. Individual accelerators may instead
         // be selected with: {node: {name: 'server name',accelerators: [0]}}
         accelerators : [
            {node_name : 'FALCON-NEST - 0'}
         ],

         // Explicit per-port addresses used by either manual assignment mode.
         // Entries correspond to network ports on the assigned accelerators.
         accelerators_ports_addresses : [
            {mac_address : '00:50:c2:f6:cc:41',ip_address : '1.11.89.1'},
            {mac_address : '00:50:c2:f6:cc:42',ip_address : '2.11.89.1'},
            {mac_address : '00:50:c2:f6:cc:43',ip_address : '1.11.93.1'},
            {mac_address : '00:50:c2:f6:cc:44',ip_address : '2.11.93.1'},
            {mac_address : '00:50:c2:f6:cc:45',ip_address : '1.11.97.1'},
            {mac_address : '00:50:c2:f6:cc:46',ip_address : '2.11.97.1'},
            {mac_address : '00:50:c2:f6:cc:47',ip_address : '1.11.101.1'},
            {mac_address : '00:50:c2:f6:cc:48',ip_address : '2.11.101.1'},
            {mac_address : '00:50:c2:f6:00:08',ip_address : '10.151.1.49'},
            {mac_address : '00:50:c2:f6:00:09',ip_address : '10.151.2.49'},
            {mac_address : '00:50:c2:f6:00:10',ip_address : '10.151.1.51'},
            {mac_address : '00:50:c2:f6:00:11',ip_address : '10.151.2.51'},
            {mac_address : '00:50:c2:f6:00:12',ip_address : '10.151.1.53'},
            {mac_address : '00:50:c2:f6:00:13',ip_address : '10.151.2.53'},
            {mac_address : '00:50:c2:f6:00:14',ip_address : '10.151.1.55'},
            {mac_address : '00:50:c2:f6:00:15',ip_address : '10.151.2.55'}
         ],

         network : {
            // Per-port MAC assignment:
            //   'manual': use mac_address values above
            //   'auto': generate sequential MACs from the start value
            mac_address_assignment_mode : 'manual',
            auto_mac_address_start       : '00:50:c2:f6:cc:00',
            auto_mac_address_inc         : 1,
            // Per-port IP assignment:
            //   'manual': use ip_address values above
            //   'auto': allocate the requested count sequentially from the start
            ip_address_assignment_mode   : 'manual',
            auto_ip_address_start        : '172.16.250.0',
            auto_ip_address_num          : 16,
            // Ingress routing modes:
            //   'sps': ST 2022-7 seamless protection switching
            //   'auto': load balance across both AFU network interfaces
            //   'afu0'/'afu1': receive only on the selected interface
            ingress_sources_routing_mode : 'sps'
         },

         // Remove discovered sources that are no longer in use when the
         // configuration is applied.
         clear_unused_sources : true,
         // PTP synchronization and domain used by this cluster.
         ptp_enable            : true,
         ptp_domain_number     : 50,
         // Ember+ control server port.
         ember_port            : 9000,

         // TSL UMD v5 tally/label connections. Heads are distributed across
         // connections_num connections, with at most screens_per_connection
         // heads on each connection.
         tsl : {
            connections_num        : 1,
            screens_per_connection : 65535,
            udp_port               : 8800,
            tcp_port               : 8801
         },
         // Optional Plura timer sources.
         plura_timers : ['172.16.0.231'],

         // IS-04/IS-05 registry URL and the host addresses advertised for
         // senders/receivers. Advertised hosts are normally server management
         // IP addresses.
         nmos : {
            registry_url    : 'http://172.16.0.118:8010',
            advertised_hosts: ['172.16.209.73']
         },

         // Multicast pools from which services allocate output addresses. A
         // primary range is followed by its paired secondary range for SPS/
         // ST 2022-7. ip_addresses_range_id on a service refers to the
         // zero-based position in this array.
         //
         // Fields:
         //   ip_addresses_start: first multicast address in the block
         //   ip_addresses_num: number of addresses available
         //   inc_mode: address increment order ('X_X_1_1' or 'X_1_X_1')
         //   sources_routing_mode: 'sps', 'auto', 'afu0', or 'afu1'
         //   udp_src_port/udp_dst_port: RTP/UDP transport ports
         //   rtp_payload_type: RTP payload type for generated streams
         services_ip_addresses_ranges : [
            {name : 'RL Generators IP Range',ip_addresses_start : '237.0.0.0',ip_addresses_num : 8192,inc_mode : 'X_X_1_1',sources_routing_mode : 'sps',udp_src_port : 9000,udp_dst_port : 9000,rtp_payload_type : 96},
            {name : 'RL Generators IP Range',ip_addresses_start : '237.1.0.0',ip_addresses_num : 8192,inc_mode : 'X_X_1_1',sources_routing_mode : 'sps',udp_src_port : 9000,udp_dst_port : 9000,rtp_payload_type : 96},
            {name : 'Video Test Patterns IP Range Primary',ip_addresses_start : '237.0.16.0',ip_addresses_num : 1024,inc_mode : 'X_X_1_1',sources_routing_mode : 'sps',udp_src_port : 9000,udp_dst_port : 9000,rtp_payload_type : 96},
            {name : 'Video Test Patterns IP Range Secondary',ip_addresses_start : '237.1.16.0',ip_addresses_num : 1024,inc_mode : 'X_X_1_1',sources_routing_mode : 'sps',udp_src_port : 9000,udp_dst_port : 9000,rtp_payload_type : 96},
            {name : 'Multiviewer Heads IP Range Primary',ip_addresses_start : '239.111.89.0',ip_addresses_num : 1024,inc_mode : 'X_X_1_1',sources_routing_mode : 'sps',udp_src_port : 9020,udp_dst_port : 9020,rtp_payload_type : 97},
            {name : 'Multiviewer Heads IP Range Secondary',ip_addresses_start : '239.211.89.0',ip_addresses_num : 1024,inc_mode : 'X_X_1_1',sources_routing_mode : 'sps',udp_src_port : 9020,udp_dst_port : 9020,rtp_payload_type : 97}
         ]
      }
   ]
};

// =============================================================================
// IMPLEMENTATION
// =============================================================================

function get_layouts()
{
   // Layouts are generated from family-level parameters rather than being
      // defined individually (for example, every 2x2, 3x3, or featured layout).
   let parameters        = generate_layouts_parameters();

      // Select which families are available in every PIP style:
      //   standard_layouts_enable: regular grids (1-, 4-, 9-, 16-way, etc.)
      //   layouts_enable: asymmetric/featured layouts (6-, 7-, 8-way, etc.)
      //   remote/director/vt_coord: specialized operational layouts
      //   big/riot: additional large and Riot-specific layout families
      for(let i = 0; i < LAYOUTS_CONFIGS_NUM;i++)
      {
         parameters.pip_configurations[i].standard_layouts_enable = layout_configuration.families.standard;
         parameters.pip_configurations[i].layouts_enable          = layout_configuration.families.featured;
         parameters.pip_configurations[i].remote_layouts_enable   = layout_configuration.families.remote;
         parameters.pip_configurations[i].director_layouts_enable = layout_configuration.families.director;
         parameters.pip_configurations[i].vt_coord_layouts_enable = layout_configuration.families.vt_coord;
         parameters.pip_configurations[i].big_layouts_enable      = layout_configuration.families.big;
         parameters.pip_configurations[i].riot_layouts_enable     = layout_configuration.families.riot;
      }

      // Set the default text source for every existing UMD and OMD cell. Supply
      // one mode for all cells or an array for per-cell mapping; if a display
      // has more cells than entries, the last entry is reused.
      //
      // Monitor-display mode options:
      //   'label', 'parent_video_source_name',
      //   'parent_video_source_standard', 'parent_video_source_tally_label',
      //   'parent_video_source_user_label_0',
      //   'parent_video_source_user_label_1',
      //   'parent_video_source_standard_interface',
      //   'parent_video_source_standard_tcs'.
      {
         configure_existing_umd_modes(parameters,layout_configuration.default_umd_modes);
         configure_existing_omd_modes(parameters,layout_configuration.default_omd_modes);
      }

       // Example of deriving a custom layout style from an existing family.
       // get_default_md(2) creates a two-cell UMD (Under Monitor Display).
       {
         apply_custom_umd_layout(parameters);
         apply_layout_alarm_configuration(parameters);
      }

      // Configure PPM meter count, channel mapping, and adaptive width for all
      // built-in PPM layout styles. Channel counts and offsets accept either a
      // number applied to every meter or an array with one value per meter.
      {
         apply_ppm_configuration(parameters,layout_configuration.ppm);
      }

      // Enable only the PIP styles that should be generated. Disabling unused
      // styles avoids creating hundreds of unnecessary layout records.
      // "outside" places UMD/PPM elements around the video; "inside" overlays
      // them on the video. TALLY variants add tally indication.
      {
         for(const [style_id,enable] of Object.entries(layout_configuration.enabled_styles))
            parameters.pip_configurations[Number(style_id)].enable = enable;
      }
      // Enable and style the 1920x1080 layout raster.
      {
         apply_raster_configuration(parameters);
      }
      let layouts                   = generate_all_layouts(parameters);
      return layouts;

}

function get_services()
{
  // Services are emitted in the API's schema/table/records form. The loop bound
  // controls how many instances of each service type are created; a bound of 0
  // disables that service block.
  //
  // Common video_raster_id values:
  //   '720x486', '720x576', '1280x720', '1920x1035', '1920x1080',
  //   '2048x1080', '3840x2160', '4096x2160', '7680x4320', '8192x4320'.
  // Common video_refresh_rate_id values:
  //   'p23.98Hz', 'sF23.98Hz', 'p24Hz', 'sF24Hz', 'p25Hz', 'sF25Hz',
  //   'p29.97Hz', 'sF29.97Hz', 'p30Hz', 'sF30Hz', 'p47.95Hz',
  //   'i47.95Hz', 'p48Hz', 'i48Hz', 'p50Hz', 'i50Hz', 'p59.94Hz',
  //   'i59.94Hz', 'p60Hz', 'i60Hz', 'p100Hz', 'p119.88Hz', 'p120Hz'.
  let  services = <any>[];

  let child_id = 0;

  // Video test generators create synthetic video streams. pattern_type chooses
  // the image/motion pattern, and ip_addresses_range_id selects the output
  // multicast range defined later in this file.
  for(let i = 0; i < service_configuration.video_test_generators.count;i++)
    {
      let pattern_types     = ['colour','counter v','counter h','counter hv','counter vh'];
      let pattern_type_id   = service_configuration.video_test_generators.pattern_start_index+i%4;
      let pattern_type      = pattern_types[pattern_type_id];

      let video_testgen = {
        db_schema                                : 'video',
        db_table                                 : 'test_generators',
        db_table_records                         :
        [
          {
             //user_afu_id                        :  2,
            name                               : `Video TP ${i}`,
            //video standard
            video_raster_id                    : service_configuration.video_test_generators.video_raster_id,
            video_refresh_rate_id              : service_configuration.video_test_generators.video_refresh_rate_id,
            //test_generator specific
            pattern_type                       : pattern_type,
            inserted_id                        : i,
            inserted_id_enable                 : service_configuration.video_test_generators.inserted_id_enable,
            frame_id                           : service_configuration.video_test_generators.frame_id,
            input_frames_num                   : service_configuration.video_test_generators.input_frames_num,
            colour_c0                          : service_configuration.video_test_generators.colour_c0,
            colour_c1                          : service_configuration.video_test_generators.colour_c1,
            colour_c2                          : service_configuration.video_test_generators.colour_c2,
            //
            insert_motion_enable               : service_configuration.video_test_generators.insert_motion_enable,
            insert_motion_colour               : service_configuration.video_test_generators.insert_motion_colour,
            enable_output_rl                   : service_configuration.video_test_generators.enable_output_rl,
            ip_addresses_range_id              : service_configuration.video_test_generators.ip_addresses_range_id,
            output_stream_enable               : service_configuration.video_test_generators.output_stream_enable
        }
      ]
      };
      services[child_id++] = video_testgen;
    }



    const heads_description = service_configuration.multiviewer_heads;


 // Generate multiviewer heads

  for(let i = 0; i < heads_description.length;i++)
  {

    let multiviewer_head = {
      db_schema         : 'video',
      db_table          : 'multiviewer_heads',
      db_table_records   : [
              {
                //user_afu_id                             : heads_description[i].user_afu_id,  //Used to pin a service to a dedicated AFU. Comment out for auto load balance
                name                                    : heads_description[i].name,
                video_inputs_max_num                    : heads_description[i].video_inputs_max_num,
                audio_inputs_max_num                    : heads_description[i].audio_inputs_max_num,
                metadata_inputs_max_num                 : heads_description[i].metadata_inputs_max_num,
                audio_inputs_per_video_input_max_num    : service_configuration.multiviewer_defaults.audio_inputs_per_video_input_max_num,
                metadata_inputs_per_video_input_max_num : service_configuration.multiviewer_defaults.metadata_inputs_per_video_input_max_num,
                display_mode                            : service_configuration.multiviewer_defaults.display_mode,
                video_raster_id                         : heads_description[i].video_raster_id,
                video_refresh_rate_id                   : heads_description[i].video_refresh_rate_id,
                layout_id                               : heads_description[i].layout_id,
                ip_addresses_range_id                   : service_configuration.multiviewer_defaults.ip_addresses_range_id
             }
      ]
    };
    services[child_id++] = multiviewer_head;
  }
  // UDX services perform video format conversion. Their output multicast
  // addresses are allocated from the selected ip_addresses_range_id.
  for(let i = 0; i < service_configuration.udx.count;i++)
  {
    let udx = {
      db_schema                                : 'video',
      db_table                                 : 'udxs',
      db_table_records                         :
      [
        {
             //user_afu_id                        : 1,
            name                               : `UDX ${i}`,
            //video standard
            video_raster_id                    : service_configuration.udx.video_raster_id,
            video_refresh_rate_id              : service_configuration.udx.video_refresh_rate_id,
            //
            ip_addresses_range_id              : service_configuration.udx.ip_addresses_range_id
        }
      ]
    };
    services[child_id++] = udx;
  }

  return services;
}

async function get_luts3D()
{
  // Import every Type III .cube file in this directory. The filename becomes
  // the LUT title and the complete file contents are sent as lut_data.
  const folderPath = luts_directory;
  const files: string[] = await fs.readdir(folderPath);
  const cubeFiles = await files.filter((file) => { return path.extname(file).toLowerCase() === '.cube';});

  //console.log(`files: ${files}`);


  let  luts = <any>[];
  let child_id = 0;

  for (const file of cubeFiles)
  {
    const nameWithoutExt = path.parse(file).name;
    const filePath: string = path.join(folderPath, file);

    const stats = await fs.stat(filePath);
    if(stats.isFile())
    {
      console.log(`file: ${file} lut_name ${nameWithoutExt} Full path: ${filePath}`);
      const fileContent: string =  await fs.readFile(filePath, 'utf-8');
      const lut = {
              title    : nameWithoutExt,
              lut_data : fileContent
            };
      luts[child_id++] = lut;
    }
  }

  return luts;
}

// MANIFOLD_JOBS_WS_URL may override the API client's default local jobs socket.
const api = new ManifoldCloudAPI(api_configuration.url);


async function run() {

    try {

        await api.login(api_configuration.username,api_configuration.password);

        // The payload contains both cloud-wide resources and cluster-specific
        // configuration. Array order supplies the local ids referenced by fields
        // such as ip_addresses_range_id.
        const cloud_configuration_payload = await build_cloud_configuration_payload();

        // Pair the area-selection filter with its replacement configuration.
        const cloud_configuration =
        {
          filter  : configuration_areas,
          payload : cloud_configuration_payload
        } ;

        // Applying hardware, layouts, LUTs, and services may take several
        // minutes, so wait for the asynchronous configuration job to complete.
        const configuration_result = await api.post_and_wait(
          '/configuration',cloud_configuration,api_configuration.timeout);

        console.log('configuration result:',configuration_result);


    } catch (err: any) {
      console.error('API Error:', err.message);
    }
  }

// -----------------------------------------------------------------------------
// IMPLEMENTATION HELPERS
// -----------------------------------------------------------------------------
// The editable choices live near the top of the file. The translation from a
// named PPM preset to the layout generator's individual arguments stays here.

type PpmConfigurationMode = 'preset' | 'manual';
type PpmPreset = 'split_16ch' | 'mirrored_8ch' | 'quad_4ch_zero';

type PpmLayoutConfiguration = {
   mode              : PpmConfigurationMode,
   preset            : PpmPreset,
   meters_left       : number,
   channels_left     : PpmValueConfiguration,
   offset_left       : PpmValueConfiguration,
   meters_right      : number,
   channels_right    : PpmValueConfiguration,
   offset_right      : PpmValueConfiguration,
   width             : number,
   width_max         : number,
   channel_min_width : number
};

function apply_custom_umd_layout(parameters: ReturnType<typeof generate_layouts_parameters>)
{
   const configuration = layout_configuration.custom_umd_layout;
   const layout = clone(parameters.pip_configurations[configuration.based_on]);

   layout.name = configuration.name;
   layout.video_source.style_border_width = configuration.video_border_width;
   layout.umd = get_default_md(configuration.cells.length);
   layout.umd.alignment = configuration.alignment;
   layout.umd.width = configuration.width;

   configuration.cells.forEach((cell,index) => {
      layout.umd.cells[index].mode = cell.mode;
      layout.umd.cells[index].width = cell.width;
      layout.umd.cells[index].style_border_width = cell.border_width;
   });

   parameters.pip_configurations[configuration.slot] = layout;
}

function apply_layout_alarm_configuration(parameters: ReturnType<typeof generate_layouts_parameters>)
{
   const configuration = layout_configuration.alarms;
   const video_source = parameters.pip_configurations[configuration.style].video_source;
   video_source.alarms_enable = configuration.enable;
   video_source.alarms_on_video_source_not_assigned_show_logo = configuration.show_logo_when_unassigned;
}

function apply_raster_configuration(parameters: ReturnType<typeof generate_layouts_parameters>)
{
   for(const [raster_id,configuration] of Object.entries(layout_configuration.rasters))
   {
      const raster = parameters.raster_configurations[Number(raster_id)];
      raster.enable = configuration.enable;
      raster.layout_style_bgnd_color = configuration.background;
   }
}

async function build_cloud_configuration_payload()
{
   const clusters = hardware_configuration.clusters.map(configuration => ({
      accelerators                 : configuration.accelerators,
      accelerators_ports_addresses : configuration.accelerators_ports_addresses,
      cluster : {
         name                                      : configuration.name,
         id_uuid                                   : configuration.id_uuid,
         network_ports_mac_address_assignment_mode : configuration.network.mac_address_assignment_mode,
         network_ports_auto_mac_address_start       : configuration.network.auto_mac_address_start,
         network_ports_auto_mac_address_inc         : configuration.network.auto_mac_address_inc,
         network_ports_address_assignment_mode      : configuration.network.ip_address_assignment_mode,
         network_ports_auto_ip_address_start        : configuration.network.auto_ip_address_start,
         network_ports_auto_ip_address_num          : configuration.network.auto_ip_address_num,
         clear_unused_sources                       : configuration.clear_unused_sources,
         ingress_sources_routing_mode               : configuration.network.ingress_sources_routing_mode,
         ptp_enable                                 : configuration.ptp_enable,
         ptp_domain_number                          : configuration.ptp_domain_number,
         ember_port                                 : configuration.ember_port,
         tsl_connections_num                        : configuration.tsl.connections_num,
         tsl_screens_per_connection                 : configuration.tsl.screens_per_connection,
         tsl_udp_port                               : configuration.tsl.udp_port,
         tsl_tcp_port                               : configuration.tsl.tcp_port,
         nmos_registry_url                          : configuration.nmos.registry_url,
         nmos_advertised_hosts                      : configuration.nmos.advertised_hosts,
         plura_timers                               : configuration.plura_timers
      },
      services_ip_addresses_ranges : configuration.services_ip_addresses_ranges,
      services                     : get_services()
   }));

   return {
      nodes    : hardware_configuration.nodes,
      licenses : hardware_configuration.licenses,
      clusters,
      layouts  : get_layouts(),
      luts3D   : await get_luts3D()
   };
}

function apply_ppm_configuration(
   parameters: ReturnType<typeof generate_layouts_parameters>,
   configuration: PpmLayoutConfiguration)
{
   let meters_left    = configuration.meters_left;
   let channels_left  = configuration.channels_left;
   let offset_left    = configuration.offset_left;
   let meters_right   = configuration.meters_right;
   let channels_right = configuration.channels_right;
   let offset_right   = configuration.offset_right;

   if(configuration.mode == 'preset')
   {
      switch(configuration.preset)
      {
         case 'split_16ch':
            meters_left = 1;
            channels_left = 8;
            offset_left = 0;
            meters_right = 1;
            channels_right = 8;
            offset_right = 8;
            break;
         case 'mirrored_8ch':
            meters_left = 1;
            channels_left = 8;
            offset_left = 0;
            meters_right = 1;
            channels_right = 8;
            offset_right = 0;
            break;
         case 'quad_4ch_zero':
            meters_left = 2;
            channels_left = 4;
            offset_left = 0;
            meters_right = 2;
            channels_right = 4;
            offset_right = 0;
            break;
      }
   }

   configure_default_ppm_layouts(parameters,
                                 meters_left,
                                 channels_left,
                                 offset_left,
                                 meters_right,
                                 channels_right,
                                 offset_right,
                                 configuration.width,
                                 configuration.width_max,
                                 configuration.channel_min_width);
}

run();
